import { Inter } from 'next/font/google'
import AuthProvider from './components/AuthProvider'
import TokenContextProvieder from '@/context/TokenContextProvieder'
import '@/styles/globals.css'

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '700', '900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TokenContextProvieder>
        <body className={inter.className}>
          <AuthProvider>
            {children}
          </AuthProvider>
        </body>
      </TokenContextProvieder>
    </html>
  )
}
